# Site settings
title:  샘둥이의 블로그
header-img: img/smnkim.jpg
email: saemina.kim@nhnent.com
description: ""
baseurl: ""
url: "http://smnkim.github.io"
github_username:  smnkim
facebook_username: kimseamina
comments: yes

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
gems: [jekyll-paginate]
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
