# Site settings
title:  smnkim
header-img: img/smnkim.jpg
email: saemina.kim@nhnent.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://smnkim.github.io"
github_username:  smnkim
facebook_username: kimseamina
comments: yes

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
gems: [jekyll-paginate]
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
